//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ten kod źródłowy został wygenerowany automatycznie przez Microsoft.VSDesigner, wersja 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SprawdzVAT.statusService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_WeryfikacjaVAT", Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")]
    public partial class WeryfikacjaVAT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SprawdzNIPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SprawdzNIPNaDzienOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WeryfikacjaVAT() {
            this.Url = global::SprawdzVAT.Properties.Settings.Default.SprawdzVAT_statusService_WeryfikacjaVAT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SprawdzNIPCompletedEventHandler SprawdzNIPCompleted;
        
        /// <remarks/>
        public event SprawdzNIPNaDzienCompletedEventHandler SprawdzNIPNaDzienCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("WynikOperacji", Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")]
        public TWynikWeryfikacjiVAT SprawdzNIP([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")] string NIP) {
            object[] results = this.Invoke("SprawdzNIP", new object[] {
                        NIP});
            return ((TWynikWeryfikacjiVAT)(results[0]));
        }
        
        /// <remarks/>
        public void SprawdzNIPAsync(string NIP) {
            this.SprawdzNIPAsync(NIP, null);
        }
        
        /// <remarks/>
        public void SprawdzNIPAsync(string NIP, object userState) {
            if ((this.SprawdzNIPOperationCompleted == null)) {
                this.SprawdzNIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSprawdzNIPOperationCompleted);
            }
            this.InvokeAsync("SprawdzNIP", new object[] {
                        NIP}, this.SprawdzNIPOperationCompleted, userState);
        }
        
        private void OnSprawdzNIPOperationCompleted(object arg) {
            if ((this.SprawdzNIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SprawdzNIPCompleted(this, new SprawdzNIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIPNaDzien", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("WynikOperacji", Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")]
        public TWynikWeryfikacjiVAT SprawdzNIPNaDzien([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")] string NIP, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")] System.DateTime Data) {
            object[] results = this.Invoke("SprawdzNIPNaDzien", new object[] {
                        NIP,
                        Data});
            return ((TWynikWeryfikacjiVAT)(results[0]));
        }
        
        /// <remarks/>
        public void SprawdzNIPNaDzienAsync(string NIP, System.DateTime Data) {
            this.SprawdzNIPNaDzienAsync(NIP, Data, null);
        }
        
        /// <remarks/>
        public void SprawdzNIPNaDzienAsync(string NIP, System.DateTime Data, object userState) {
            if ((this.SprawdzNIPNaDzienOperationCompleted == null)) {
                this.SprawdzNIPNaDzienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSprawdzNIPNaDzienOperationCompleted);
            }
            this.InvokeAsync("SprawdzNIPNaDzien", new object[] {
                        NIP,
                        Data}, this.SprawdzNIPNaDzienOperationCompleted, userState);
        }
        
        private void OnSprawdzNIPNaDzienOperationCompleted(object arg) {
            if ((this.SprawdzNIPNaDzienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SprawdzNIPNaDzienCompleted(this, new SprawdzNIPNaDzienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")]
    public partial class TWynikWeryfikacjiVAT {
        
        private TKodWeryfikacjiVAT kodField;
        
        private string komunikatField;
        
        /// <remarks/>
        public TKodWeryfikacjiVAT Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        public string Komunikat {
            get {
                return this.komunikatField;
            }
            set {
                this.komunikatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")]
    public enum TKodWeryfikacjiVAT {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        X,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SprawdzNIPCompletedEventHandler(object sender, SprawdzNIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SprawdzNIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SprawdzNIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TWynikWeryfikacjiVAT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TWynikWeryfikacjiVAT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SprawdzNIPNaDzienCompletedEventHandler(object sender, SprawdzNIPNaDzienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SprawdzNIPNaDzienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SprawdzNIPNaDzienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TWynikWeryfikacjiVAT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TWynikWeryfikacjiVAT)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591